<?php 
/*                                                                       *
* This script is part of the findologic search project			         *
*                                                                        *
* logo is free software; you can redistribute it and/or modify  *
* it under the terms of the GNU General Public License version 2 as      *
* published by the Free Software Foundation.                             *
*                                                                        *
* This script is distributed in the hope that it will be useful, but     *
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHAN-    *
* TABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General      *
* Public License for more details.                                       *
*                                                                        *
* @version $Id: logo.phtml 301 2010-05-03 07:56:59Z weller $
* @license http://opensource.org/licenses/gpl-license.php GNU Public License, version 2
*/

?>
<?php if(Mage::helper('findologic')->isAlive()):?>
<div style="text-align: right">
	<a href="http://www.findologic.com/" target="_blank">
		<img src="<?php echo $this->getLogoUrl(); ?>" alt="<?php echo $this->__('Searchtechnology by FINDOLOGIC'); ?>"/>
	</a>
</div>
<?php endif;?>